# Generated by Django 2.2.11 on 2020-03-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_remove_pur_nam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pur',
            name='purchaser',
        ),
        migrations.AddField(
            model_name='pur',
            name='nam',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
