# Generated by Django 2.2.11 on 2020-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_auto_20200321_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pur',
            name='nam',
            field=models.CharField(max_length=200),
        ),
    ]
