# Generated by Django 3.0.4 on 2020-03-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_auto_20200321_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='img/index.jpeg', upload_to='img/')),
            ],
        ),
    ]
